packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  cpu-features: false
  protobufjs: false
  ssh2: false

autoInstallPeers: false
engineStrict: true
minimumReleaseAge: 1440
onlyBuiltDependencies:
  - esbuild
savePrefix: ""
strictPeerDependencies: true
verifyStoreIntegrity: true
